spring:
  application:
    name: gateway
  config:
    import:
    - optional:configserver:http://admin:nimda@myserver:8082/configserver  
  cloud:
    config:      
      fail-fast: true
      uri:
      - http://admin:nimda@myserver:8082/configserver
    discovery:
      enabled: true   
      
      
      
      
eureka:
  client:
    service-url:
      defaultZone: http://admin:nimda@myserver:8082/eureka/
    register-with-eureka: true        
  instance:
    prefer-ip-address: false
    hostname: myserver
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      configPath: /configserver
      
      
    