spring:
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: auth
        uri: lb://AUTH-SERVER
        predicates:
        - Path=/auth/**   
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}  application:    name: gateway
  
      
eureka:  client:    service-url:      defaultZone: http://admin:nimda@myserver:8082/eureka/
    register-with-eureka: true          instance:    prefer-ip-address: false
    hostname: myserver
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    

server:
  port: 1443
 